name: pdf_uploader
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  aura_box: ^1.0.1
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.0
  file_picker: ^6.1.1
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.1
  flutter_pdf_text: ^0.7.0
  flutter_pdfview: ^1.3.2
  google_fonts: ^4.0.4
  http: ^1.2.1
  lottie: ^2.6.0
  path_provider: ^2.1.2
  rflutter_alert: ^2.0.7
  syncfusion_flutter_pdf: ^24.2.9
  toasty_box: ^1.0.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/Pdf_Quizzer.png"
  min_sdk_android: 16
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "images/Pdf_Quizzer.png"

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/translations/
    - assets/translations/en.json
