name: pdf_uploader
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  audioplayers: ^6.2.0
  aura_box: ^1.0.1
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.0
  file_picker: ^9.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.1
  flutter_pdfview: ^1.3.2
  google_fonts: ^4.0.4
  http: ^1.2.1
  lottie: ^2.6.0
  path_provider: ^2.1.2
  rflutter_alert: ^2.0.7
  shared_preferences: ^2.5.2
  syncfusion_flutter_pdf: ^28.2.11
  toasty_box: ^1.0.4
  flutter_native_splash: ^2.4.4
  sqflite: ^2.4.0
  path: ^1.9.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/pdf_quizzer.png"
  min_sdk_android: 16
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "images/Pdf_Quizzer.png"

flutter_native_splash:
  color: "#ffffff"
  image: "images/pdf_quizzer_logo.png"
  android: true
  ios: true

  # Optional customization
  android_12:
    image: "images/pdf_quizzer_logo.png"
    color: "#ffffff"

  # If you want a fullscreen splash
  fullscreen: false

  # You can use your app theme as background
  # color_dark and image_dark for dark mode
  # color_dark: "#121212"
  # image_dark: "images/pdf_quizzer_dark.png"


dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/translations/
    - assets/translations/en.json
    - assets/sounds/
